CREATE DATABASE dragunwf_DB

CREATE TABLE Customers (
 CustomerID INT PRIMARY KEY NOT NULL,
 FirstName VARCHAR(50) NOT NULL,
 LastName VARCHAR(50) NOT NULL,
 Email VARCHAR(50) NOT NULL,
 Gender VARCHAR(50) NOT NULL,
 Birthdate DATE NOT NULL
);

CREATE TABLE Vendors (
 VendorID INT PRIMARY KEY NOT NULL,
 Name VARCHAR(50) NOT NULL,
 ContactNum VARCHAR(50) NOT NULL,
 CityAddress VARCHAR(100) NOT NULL
);

CREATE TABLE Products (
 ProductID INT PRIMARY KEY,
 Description VARCHAR(2000) NOT NULL,
 Quantity INT NOT NULL,
 Price DECIMAL NOT NULL,
 VendorID INT FOREIGN KEY REFERENCES Vendors(VendorID)
);